### ISSUE TITLE
Sugerencia para Skyblock

### ISSUE THREAD

**Issue by SansWarYT** [DorrD/MagieNetwork#3]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Una descripción clara y concisa de cuál es el problema. Ejemplo: Siempre me frustra cuando [...]
Basicamente en skyblock, quiero hacer una granja de oro que te da bastante oro por hora, pero el problema es que no hay magma en la tienda, quitando mis posibilidades de hacer una granja.
**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que suceda.
Me gustaria que se metiera la magma o el magma block en la tienda de isla, ya que me habilitaria a no solo poder construir con ello pero hacer granjas.
**Describe las alternativas que has considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.
Pues lo que dije arriba,  ya que hacer otra cosa no tendria sentido.
**¿Algo más?** (opcional)
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.
Creo que esta bastante clara mi sugerencia.

**Comment by Ryzer03** [comment]
Por ahora no tenemos pensado implementar magma.
