### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Amurciano12** [DorrD/MagieNetwork#5]
**Describe el error**
Una descripción clara y concisa de cuál es el error.
-Los Tokens del Hub no se ven.

**Versión de tu MC**
Puede ser desde la 1.16 hasta la 1.16.5
-1.16.5.
**Versión del Servidor**
Para saber la versión en la que estás haciendo esto, usa en el servidor el comando */magie*
2.4833.07-sv.

**Capturas (Medios)**
Coloca aquí una captura o vídeo del problema.
![2021-03-27_00 15 27](https://user-images.githubusercontent.com/81106900/112701691-9cfa8d00-8e91-11eb-8959-e41eec7949df.png)

**Comment by MilkkaCute** [comment]
Este error no lo conocíamos, lo resolveremos lo más pronto posible. Muchas gracias por reportarlo.
