### ISSUE TITLE
Spawners

### ISSUE THREAD

**Issue by Amurciano12** [DorrD/MagieNetwork#6]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Una descripción clara y concisa de cuál es el problema. Ejemplo: Siempre me frustra cuando [...]
-Me gustaría que en Skyblock se pudiera comprar Spawners por un precio considerable mín: 1,5M 
**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que suceda.
-Ponerla en la tienda de Skyblock ya que eso daria bastante jugabilidad a Skyblock
**Describe las alternativas que has considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.
-Me gustaria que hubiera la posibilidad de tener granjas con spawners!
**¿Algo más?** (opcional)
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.

**Comment by Amurciano12** [comment]
1.

**Comment by Amurciano12** [comment]
Perdón le di sin querer

**Comment by MilkkaCute** [comment]
Lo lamentamos, por ahora no tenemos pensado añadir spawners a la venta en el SkyBlock.
