### ISSUE TITLE
Aldeano

### ISSUE THREAD

**Issue by Amurciano12** [DorrD/MagieNetwork#7]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Una descripción clara y concisa de cuál es el problema. Ejemplo: Siempre me frustra cuando [...]
Posibilidad de tener aldeanos mas facilmente
**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que suceda.
Subir la posibilidad de aparecer un Zombie Villager o poder conseguirlo de algun otro metodo
**Describe las alternativas que has considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.
Poder conseguir tipo unos fragmentos de aldeano cada 5 zombies aldeano sacrificados
**¿Algo más?** (opcional)
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.

**Comment by Ryzer03** [comment]
¡Claro! Lo implementaremos estos próximos días. Una manera sencilla, de conseguir aldeanos o alguna otra entidad también.
